# Generated by Django 4.0.5 on 2022-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.IntegerField(default=0)),
                ('finishers', models.IntegerField(default=0)),
                ('pupils', models.IntegerField(default=0)),
                ('special_courses', models.IntegerField(default=0)),
            ],
        ),
    ]
