# Generated by Django 4.0.5 on 2022-06-05 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
