# Generated by Django 4.0.5 on 2022-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0005_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
