# Generated by Django 4.0.5 on 2022-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0008_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='10-oy', max_length=100),
            preserve_default=False,
        ),
    ]
