# Generated by Django 4.0.5 on 2022-06-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0009_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='staf',
            name='user_type',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Director', 'Director')], default='Teacher', max_length=10, null=True),
        ),
    ]
