# Generated by Django 4.0.5 on 2022-06-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0010_event_image_alter_staf_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
