# Generated by Django 4.0.5 on 2022-06-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0011_alter_event_options_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
