# Generated by Django 4.0.5 on 2023-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolweb', '0012_opinion_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='bio_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='schoolweb.staf'),
        ),
        migrations.AlterField(
            model_name='staf',
            name='user_type',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Teacher', max_length=10, null=True),
        ),
    ]
